# Elle okunan SINIR kayıtları — karar ve gerekçe
# Format: sıra: (karar, gerekçe)
MANUAL = {
 158:("OUT","mekanizma: circRNA sponge düzenleyici rol"),
 513:("OUT","tedavi/ilaç etkinliği, organoid model"),
 569:("IN","idrar temelli sürücü gen mutasyonu + anöploidi ile noninvaziv tanı"),
 645:("KONTROL","üroloji geneli ML derlemesi — mesane odak mı, tam başlık gerek"),
 686:("IN","ctDNA ile metastatik mesane genomu — kan temelli sıvı biyopsi"),
 704:("OUT","mekanizma: miRNA hücre agresifliği düzenlemesi"),
 731:("OUT","mekanizma: circRNA sponge"),
 734:("IN","DWI doku özellikleriyle radyomik derecelendirme"),
 765:("OUT","mekanizma: eksozomal miR-21 makrofaj PI3K/AKT"),
 893:("OUT","§6: yalnızca üst üriner sistem (UTUC)"),
 934:("IN","MRG T-evrelemesi meta-analizi — §6 tanısal doğruluk meta-analizi dahil"),
1010:("OUT","mekanizma + kemosensitivite"),
1081:("IN","idrar ekstraselüler vezikül miR-21-5p belirteci"),
1102:("OUT","genel tanı/evreleme derlemesi; mavi ışık sistoskopi ve NBI eş-konu (invaziv)"),
1112:("OUT","mekanizma: UHRF1/miR-145"),
1125:("IN","hücre yüzeyi nanoçözünürlük görüntüleme + ML ile noninvaziv tanı"),
1151:("IN","tanı ve takip belirteçleri derlemesi"),
1167:("OUT","mekanizma: eksozomal BCYRN1 lenfatik metastaz"),
1218:("OUT","mekanizma: eksozomal miR-9-3p"),
1267:("IN","dolaşan tümör hücrelerinde PD-L1 — kan temelli sıvı biyopsi"),
1308:("IN","ctDNA kapsamlı genomik profilleme"),
1310:("IN","ekstraselüler veziküller noninvaziv belirteç kaynağı"),
1352:("IN","mRNA temelli idrar testi prospektif doğrulama"),
1384:("IN","mRNA temelli idrar testi doğruluk"),
1389:("IN","hematürili hastada idrar epigenetik profil"),
1398:("OUT","invaziv (üreteroskopik biyopsi) + yalnızca UTUC"),
1715:("IN","mpMRG radyomik ile patolojik derece öngörüsü"),
1720:("IN","MRG çok bölgeli segmentasyon, CNN — K4"),
1749:("OUT","karma kohort (prostat + mesane), mesane tek odak değil — karar 2 ile tutarlı"),
1975:("OUT","mekanizma: eksozom makrofaj polarizasyonu"),
2003:("IN","idrar metilasyon paneli + FGFR3 mutasyonu"),
2006:("IN","multipleks PCR + NGS ile noninvaziv tanı"),
2017:("IN","VI-RADS geçerlilik ve güvenilirlik"),
2020:("IN","MXene elektrokimyasal biyosensör, mesane kanseri belirteçlerinin çoklu saptanması"),
2066:("IN","MoS2 FET sensör dizisi ile mesane kanseri belirteç saptama"),
2077:("IN","evreleme öncesi görüntüleme yöntemlerinin duyarlılık/özgüllük karşılaştırması"),
2080:("OUT","mekanizma: EV kaynaklı tümörigenez"),
2093:("OUT","doku metabolomiği; amaç evre bazlı yolak değişimi — mekanizma"),
2096:("OUT","mekanizma/fitokimyasal tedavi"),
2140:("IN","idrar EV proteomu"),
2141:("OUT","aktif izlem/klinik yönetim çalışması, tanı teknolojisi değil"),
2171:("IN","idrar biyopsisi ile moleküler tanı ve takip derlemesi"),
2175:("IN","U-Net ile BT ürografide segmentasyon — K4"),
2252:("IN","lokal evrelemede görüntülemenin rolü"),
2270:("OUT","yönetim/maliyet çalışması"),
2279:("OUT","DNA metilasyonu tedavi hedefi olarak"),
2310:("IN","idrar-DNA testi prospektif körlemeli değerlendirme"),
2473:("IN","idrar EV proteinleri karakterizasyonu"),
2559:("OUT","periostin knockdown/in vitro invazyon — mekanizma çalışması"),
2571:("IN","görüntüleme güdümlü evreleme yolağı karşılaştırması"),
2596:("IN","idrar protein belirteçleri: tanı, takip"),
}

# --- İkinci denetim turu: kural tabanlı IN kovasındaki yanlış-pozitifler ---
MANUAL.update({
 115:("OUT","Nat Rev Dis Primers genel hastalık derlemesi; patogenez+tedavi kapsamlı"),
 327:("IN","idrar eksozomal lncRNA HOTAIR — belirteç keşfi (özet idrar eksozomu odaklı)"),
 549:("OUT","§5 KARAR 3 (kilitli): Shkolyar 2019, sistoskopi görüntüsüne dayalı"),
 878:("OUT","doku transkriptomiği tabanlı prognostik imza/biyoinformatik model"),
1661:("IN","idrar ve kanda mRNA/miRNA/lncRNA belirteçleri — noninvaziv"),
1819:("OUT","tümör dokusunda TERT genetik/epigenetik değişim, biyolojik davranış"),
1926:("OUT","böbrek+mesane karma derlemesi — mesane tek odak değil (645, 1749 ile tutarlı)"),
1945:("IN","idrar proteomiği ile AHNAK belirteci, sitolojiye yardımcı"),
2118:("OUT","§6 doku temelli: rutin histoloji slaytından YZ ile FGFR3 (patomik)"),
2125:("IN","idrar EV proteomiği; doku-eksudatif EV yalnızca süzgeç olarak kullanılmış"),
})

# --- Üçüncü tur: terim listesi boşluğundan kaynaklanan yanlış-negatif denetimi ---
# Motorun "teknoloji terimi yok" diye elediği, başlığında matriks+tanı taşıyan 18 kayıt okundu.
MANUAL.update({
 562:("OUT","yalnızca UTUC + doku genomiği (199 UTUC örneği) — §6 iki kez dışlıyor"),
1401:("IN","idrar mikrobiyotası ile mesane kanseri belirteci — YANLIŞ-NEGATİF DÜZELTMESİ"),
1902:("OUT","serum UCA1 ama hastalık HEPATOSELLÜLER karsinom; 'urothelial carcinoma' yalnızca gen adı"),
})
